### ISSUE TITLE
Long titles are not correctly displayed on Safari browser

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-blog#108]
Prerequisites:
Safari browser 14.0.3

Steps to reproduce:
1.Open https://addons-blog-preview-willdurand.vercel.app/blog/ in Safari browser
2. Observe how long titles are displayed

Expected results:
Long titles are correctly displayed in multiple lines 

Actual results:
Long titles are overlapped in the right side

Please see the screenshot for this issue:
<img width="831" alt="Screen Shot 2021-04-13 at 3 34 03 PM" src="https://user-images.githubusercontent.com/1583842/114554112-0854a500-9c6f-11eb-8e2d-3c10f3b252ed.png">

NOTES:
Not reproducible on Chrome and Firefox

**Comment by willdurand** [comment]
FTR: this was raised in the code review but this is what AMO does as well. I asked Victor to create this issue so that we can discuss. See also: https://github.com/mozilla/addons-frontend/issues/10289

There is a solution in the issue linked above. I am not quite sure what we should do tbh (although fixing the issue sounds like a good idea anyway).

**Comment by willdurand** [comment]
cc @muffinresearch

**Comment by bobsilverberg** [comment]
Is the issue that Safari does not support `overflow-wrap: anywhere;`? We use that for Firefox and Chrome because it does work, and was the only thing that seemed to work in some cases. TBPH, if this issue only really arises when we're dealing with long, unbroken strings of text, is that really a problem? Do we find those in the wild?

**Comment by willdurand** [comment]
> Is the issue that Safari does not support `overflow-wrap: anywhere;`?

Indeed.

> We use that for Firefox and Chrome because it does work, and was the only thing that seemed to work in some cases. TBPH, if this issue only really arises when we're dealing with long, unbroken strings of text, is that really a problem? Do we find those in the wild?

Well, it's very obvious with long unbroken strings but the rule is also useful for all kind of minor things when the site has to be fully responsive.

On a second though, I think we could support Safari by having two `overflow-wrap`, one with `anyhwere` and the other with `break-word` for Safari.

**Comment by vcarciu** [comment]
Verified as fixed in Safari :
<img width="833" alt="Screen Shot 2021-04-14 at 12 57 06 PM" src="https://user-images.githubusercontent.com/1583842/114692605-7063c380-9d21-11eb-9b95-dabe5a15cb08.png">
