### ISSUE TITLE
Deploy to -stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#148]
Let's update our CI config to deploy to -stage so that we can add this project to the list of projects to tag.

**Comment by willdurand** [comment]
@muffinresearch we should start to think about our release process for this project. EW uses tags and we don't need ops, right?

**Comment by willdurand** [comment]
I thought about this issue and maybe we could:

1. have a tag pattern to deploy to -stage
2. have a tag pattern to deploy to -prod
3. -stage/-prod configured with a CRON task to deploy the blog every X hours

With that:

1. pushing a tag would deploy the new version of the blog right away
2. deploying to -stage/-prod would use a script that would look for the _latest_ tag (using something like `git describe --abbrev=0 --match='*.*.*-stage'`)

Thoughts?

(I think it'd be handy to add a HTML comment with the datetime of the build in the base template for debugging purposes)

**Comment by willdurand** [comment]
> (I think it'd be handy to add a HTML comment with the datetime of the build in the base template for debugging purposes)

We can use the `version.json` file for that.

> have a tag pattern to deploy to -prod (`*.*.*-prod`)

We could try to use the pattern without any suffix so that it's similar to EW.

**Comment by ioanarusiczki** [comment]
@willdurand From the footer I access the old blog. https://blog.mozilla.org/addons/
I don't see it present in the More menu either

**Comment by willdurand** [comment]
> @willdurand From the footer I access the old blog. [blog.mozilla.org/addons](https://blog.mozilla.org/addons/)
> I don't see it present in the More menu either

Yes, because AMO -stage has a feature flag for linking to the new blog but it isn't enabled on -stage (only -dev).

**Comment by ioanarusiczki** [comment]
@willdurand oh, then I'm going to enable it from admin. Thanks!

**Comment by willdurand** [comment]
> @willdurand oh, then I'm going to enable it from admin. Thanks!

heh, sorry, you can't. It's a frontend flag :/

**Comment by ioanarusiczki** [comment]
@willdurand then this should be moved to the next milestone. Or just ping me here when it's done.

**Comment by willdurand** [comment]
> @willdurand then this should be moved to the next milestone. Or just ping me here when it's done.

the blog is deployed on -stage, though. Enabling the links on AMO should be a different issue in addons-frontend.

**Comment by ioanarusiczki** [comment]
@willdurand Oh, ok! It's been connected to the frontend repo for dev but I forgot, sorry
Yes, I see it being available at https://addons.allizom.org/blog/
I'll quickly add 2 things noticed:
- from https://addons.allizom.org/blog/ the second article, ( with ipsum long unbroken ipsum string) has a white background. When navigating to it , the header on https://addons.allizom.org/blog/2021/04/13/ipsumipsumipsumipsumipsumipsumipsumipsumipsumipsum-ipsumipsumipsumipsum/ is dark. I hope that's alright.  That's probably because it has no image as the rest of the articles. 
- 
- on Edge -  the font does not look so good compared to FF (like it's washed out or not so visible/clear)

![on Edge](https://user-images.githubusercontent.com/33448286/116565102-37754280-a90e-11eb-805f-9e075f811bdd.png)

I'll continue testing the issues left on Tuesday, when I'll explore some more around other browsers.
