### ISSUE TITLE
Add Pocket sharing option

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#243]
We currently only support sharing on Twitter, but discussed the possibility of adding Pocket as an option. As an example of such a widget, see the bottom of [this post](https://blog.mozilla.org/en/mozilla/news/modern-clean-new-firefox-clears-the-way-to-all-you-need-online/).

**Comment by willdurand** [comment]
> We currently only support sharing on Twitter, but discussed the possibility of adding Pocket as an option. As an example of such a widget, see the bottom of [this post](https://blog.mozilla.org/en/mozilla/news/modern-clean-new-firefox-clears-the-way-to-all-you-need-online/).

I remember but I was wondering how that would work: it's the first time I see this kind of sharing button, nice!

**Comment by willdurand** [comment]
mmm this Pocket button is an `iframe` and there is a comment saying:

> Please do not scrape this for the Pocket count.
> It is not reliable for you to use and will likely change.
> Contact us at api@getpocket.com for an official API.
> Thanks!

Therefore, I don't think we can use that button right now.. We should probably reach out to the Pocket team?

**Comment by jvillalobos** [comment]
That comment appears to be about showing a share count next to the widget, so I don't know if it applies to us. I asked some Pocket people anyway.

**Comment by jvillalobos** [comment]
Didn't get an answer yet, but here's their official button code: https://getpocket.com/publisher/button

We should also use a smaller twitter sharing button so they match up.

**Comment by jvillalobos** [comment]
Also, we don't need a counter, just the button.

**Comment by willdurand** [comment]
So we're thinking about not using the Pocket button because of the need to use a 3rd party JS lib and an `iframe`. I think it's doable without any of that and I made a Pocket button similar to the Twitter one. Thoughts?

![Screenshot 2021-06-22 at 15-54-41 What’s the best ad blocker for you - Firefox Add-on Reviews](https://user-images.githubusercontent.com/217628/122937398-3ee72400-d372-11eb-8b31-0952e7c90aae.png)

![Screen Shot 2021-06-22 at 15 56 40](https://user-images.githubusercontent.com/217628/122937662-71911c80-d372-11eb-864c-d935124cc630.png)

**Comment by willdurand** [comment]
I reduced the size of the buttons a bit:

![Screenshot 2021-06-22 at 16-59-57 What’s the best ad blocker for you - Firefox Add-on Reviews](https://user-images.githubusercontent.com/217628/122948620-5676da80-d37b-11eb-990a-223d732c05e0.png)
![Screen Shot 2021-06-22 at 16 59 46](https://user-images.githubusercontent.com/217628/122948627-58d93480-d37b-11eb-83a6-50db07f42e81.png)

**Comment by willdurand** [comment]
@jvillalobos WDYT?

**Comment by jvillalobos** [comment]
They look good to me!

**Comment by ioanarusiczki** [comment]
@willdurand 
- the button is available on AMO stage - as UX, "Pocket" has a light grey color (on your screenshots it looks a bit darker, it's MacOS probably). I verified on Win10 - FF, Chrome and Edge.

![POcket](https://user-images.githubusercontent.com/33448286/123239874-a5646300-d494-11eb-816a-c6c4bbb8fe13.png)

- I've noticed there's a bug, first time after the signup/login the pocket window is left opened at 0 sec 

![the first time after login](https://user-images.githubusercontent.com/33448286/123240431-291e4f80-d495-11eb-98f2-9c1d9836639c.png)

- after that it will close and return to the blog page (this should be the expected behavior)

![pocket behavior](https://user-images.githubusercontent.com/33448286/123240564-43582d80-d495-11eb-9375-f653f9b7d0b2.gif)

**Comment by willdurand** [comment]
> I've noticed there's a bug, first time after the signup/login the pocket window is left opened at 0 sec

That's likely a Pocket issue but it is fairly minor.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I'll try to contact someone, it is probably a known issue and it's been filed on their repos.

**Comment by ioanarusiczki** [comment]
@willdurand I filed the pocket issue here https://bugzilla.mozilla.org/show_bug.cgi?id=1718232
